server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/db_wxpay?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: yuan1234
      initial-size: 5
      min-idle: 1
      max-active: 5
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: yuan
        login-password: yuan1234
  redis:
    host: localhost
    password:
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
mybatis:
  type-aliases-package: com.yuan.java.wxpay.demo
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
wx:
  miniapp:
    appid: xxxxx
    secret: xxxxx
  pay:
    app-id: xxxx
    mch-id: xxxx
    mch-key: xxxx
    keyPath: "xxxx"
    notifyUrl: ""
  mp:
    app-id: xxxxx
    secret: xxxxxx
